In [1]:
# 그룹객체 만들기
# DataFrame객체.groupby(기준이 되는 열)

import pandas as pd
import seaborn as sns

In [2]:
titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "sex", "class", "fare", "survived"]]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [3]:
grouped = df.groupby("class", observed=True)
grouped

In [5]:
for key, group in grouped:
    print("* key:", key)
    print("* number:", len(group))
    print(group.head())
    print("\n")

* key: First
* number: 216
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1


* key: Second
* number: 184
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1


* key: Third
* number: 491
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [6]:
average = grouped.mean(numeric_only=True)
average

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [8]:
# 개별 그룹 선택하기

group3 = grouped.get_group("Third")
print(group3.head())

group1 = grouped.get_group("First")
print(group1.head())

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1

In [9]:
# 여러열을 기준으로 그룹화
# DataFrame객체.groupby(기준이 되는 열의 리스트)

df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [11]:
grouped_two = df.groupby(["class", "sex"], observed=True)

for key, group in grouped_two:
    print("* key:", key)
    print("* number:", len(group))
    print(group.head(3))
    print("\n")

* key: ('First', 'female')
* number: 94
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
11  58.0  female  First  26.5500         1


* key: ('First', 'male')
* number: 122
     age   sex  class      fare  survived
6   54.0  male  First   51.8625         0
23  28.0  male  First   35.5000         1
27  19.0  male  First  263.0000         0


* key: ('Second', 'female')
* number: 76
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
41  27.0  female  Second  21.0000         0


* key: ('Second', 'male')
* number: 108
     age   sex   class  fare  survived
17   NaN  male  Second  13.0         1
20  35.0  male  Second  26.0         0
21  34.0  male  Second  13.0         1


* key: ('Third', 'female')
* number: 144
     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1


* key: ('Third', 'male')
* number: 347
    age   sex  class    fare  survived
0  22.0  male  Third  7.2500         0
4  35.0  male  Third  8.0500         0
5   NaN  male  Third  8.4583         0

In [13]:
average_two = grouped_two.mean(numeric_only=True)
average_two

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [15]:
group3f = grouped_two.get_group(("Third", "female"))
group3f.head()

     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

In [16]:
grouped = df.groupby(["class"], observed=True)
std_all = grouped.std(numeric_only=True)
std_all

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [17]:
std_all_index = df.groupby(["class"], observed=True, as_index=False).std(numeric_only=True)
std_all_index

    class        age       fare  survived
0   First  14.802856  78.380373  0.484026
1  Second  14.001077  13.417399  0.500623
2   Third  12.495398  11.778142  0.428949

In [18]:
std_all["fare"]

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [19]:
grouped["fare"].std(numeric_only=True)

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [20]:
std_age_survived = grouped[["age", "survived"]].std(numeric_only=True)
std_age_survived

              age  survived
class
First   14.802856  0.484026
Second  14.001077  0.500623
Third   12.495398  0.428949

In [21]:
grouped.describe()

          age                                                       fare  \
        count       mean        std   min   25%   50%   75%   max  count
class
First   186.0  38.233441  14.802856  0.92  27.0  37.0  49.0  80.0  216.0
Second  173.0  29.877630  14.001077  0.67  23.0  29.0  36.0  70.0  184.0
Third   355.0  25.140620  12.495398  0.42  18.0  24.0  32.0  74.0  491.0

                   ...                 survived                                \
             mean  ...   75%       max    count      mean       std  min  25%
class              ...
First   84.154687  ...  93.5  512.3292    216.0  0.629630  0.484026  0.0  0.0
Second  20.662183  ...  26.0   73.5000    184.0  0.472826  0.500623  0.0  0.0
Third   13.675550  ...  15.5   69.5500    491.0  0.242363  0.428949  0.0  0.0


        50%  75%  max
class
First   1.0  1.0  1.0
Second  0.0  1.0  1.0
Third   0.0  0.0  1.0

[3 rows x 24 columns]

In [22]:
grouped[["class", "sex"]].value_counts()

class   sex
First   male      122
        female     94
Second  male      108
        female     76
Third   male      347
        female    144
Name: count, dtype: int64

In [23]:
# aggregate() 메서드 데이터 집계: group객체.aggregate(매핑 함수)
# agg() 메서드 데이터 집계: group객체.agg(매핑함수)

agg_mean = grouped.agg("mean", numeric_only=True)
agg_mean

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [24]:
# group객체.agg([함수1, 함수2, 함수3, ... ])
# group객체.agg({"열1": 함수1, "열2": 함수2, ... })

agg_all = grouped.agg(["min", "max"])
agg_all

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [26]:
agg_sep = grouped.agg(
    {
        "fare": ["min", "max"],
        "age": "mean"
    }
)

agg_sep

       fare                  age
        min       max       mean
class
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620

In [27]:
def min_max(x):
    return x.max() - x.min()

agg_minmax = grouped[["age", "fare"]].agg(min_max)
agg_minmax

          age      fare
class
First   79.08  512.3292
Second  69.33   73.5000
Third   73.58   69.5500

In [28]:
# 변환 Transformation

titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "sex", "class", "fare", "survived"]]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [29]:
grouped = df.groupby(["class"], observed=True)

grouped["fare"].cumsum()

0          7.2500
1         71.2833
2         15.1750
3        124.3833
4         23.2250
          ...
886     3801.8417
887    18147.4125
888     6706.9451
889    18177.4125
890     6714.6951
Name: fare, Length: 891, dtype: float64

In [30]:
df["fare_cumsum"] = grouped["fare"].cumsum()
df.head()

    age     sex  class     fare  survived  fare_cumsum
0  22.0    male  Third   7.2500         0       7.2500
1  38.0  female  First  71.2833         1      71.2833
2  26.0  female  Third   7.9250         1      15.1750
3  35.0  female  First  53.1000         1     124.3833
4  35.0    male  Third   8.0500         0      23.2250

In [31]:
# group객체.transform(매핑함수)

grouped[["fare"]].transform("cumsum")

           fare
0        7.2500
1       71.2833
2       15.1750
3      124.3833
4       23.2250
..          ...
886   3801.8417
887  18147.4125
888   6706.9451
889  18177.4125
890   6714.6951

[891 rows x 1 columns]

In [32]:
grouped[["age", "survived"]].transform("mean")

           age  survived
0    25.140620  0.242363
1    38.233441  0.629630
2    25.140620  0.242363
3    38.233441  0.629630
4    25.140620  0.242363
..         ...       ...
886  29.877630  0.472826
887  38.233441  0.629630
888  25.140620  0.242363
889  38.233441  0.629630
890  25.140620  0.242363

[891 rows x 2 columns]

In [34]:
def z_score(x):
    return (x - x.mean()) / x.std()

age_zscore = grouped["age"].transform(z_score)
age_zscore

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64

In [35]:
age_zscore2 = grouped["age"].transform(lambda x: (x - x.mean()) / x.std())
age_zscore2

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64