In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary"],
    "City": ["New York", "Los Angeles"],
    "Age": [28, 32],
    "Salary": [50000, 60000]
})

df

   Name         City  Age  Salary
0  John     New York   28   50000
1  Mary  Los Angeles   32   60000

In [2]:
df_melted = df.melt(id_vars=["Name", "City"],
                    var_name="Attribute",
                    value_name="Value")

df_melted

   Name         City Attribute  Value
0  John     New York       Age     28
1  Mary  Los Angeles       Age     32
2  John     New York    Salary  50000
3  Mary  Los Angeles    Salary  60000