In [2]:
import pandas as pd

In [3]:
dict_data = {
    "c0": [1, 2, 3],
    "c1": [4, 5, 6],
    "c2": [7, 8, 9],
    "c3": [10, 11, 12],
    "c4": [13, 14, 15]
}

df = pd.DataFrame(dict_data)

print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# pandas.DataFrame(2차원 배열,
#              index = 행 인덱스 배열,
#              columns =  열 이름 배열)

arr = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(arr, index = ["준서", "예은"], columns = ["나이", "성별", "학교"])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [6]:
# 행 인덱스 변경
# DataFrame객체.index = 행 인덱스 배열
# DataFrame객체.columns = 열 인덱스 배열

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [7]:
df.index = ["학생1", "학생2"]
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [8]:
df.columns = ["연령", "남녀", "소속"]
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [9]:
# 행 인덱스 변경 : DataFrame객체.rename(index = {기존 인덱스: 새 인덱스})
# 열 이름 변경 : DataFrame객체.rename(columns = {기존 이름: 새 이름})

matrix = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(matrix, index = ["준서", "예은"], columns = ["나이", "성별", "학교"])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [10]:
df = df.rename(columns = {
    "나이": "연령",
    "성별": "남녀",
    "학교": "소속"
})

In [11]:
df = df.rename(index = {
    "준서": "학생1",
    "예은": "학생2"
})

print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [12]:
# 행/열 삭제

# 행 삭제 : DataFrame객체.drop(행 인덱스 또는 배열, axis = 0, axis = "index")
# 열 삭제 : DataFrame객체.drop(열 이름 또는 배열, axis = 1, axis = "columns")

# DataFrame() 함수로 데이터프레임 변환, 변수 df에 저장
exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [13]:
df3 = df.copy()
df3 = df3.drop(["우현", "인아"], axis=0)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [14]:
df4 = df.copy()
df4 = df4.drop(["우현", "인아"], axis="index")
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [15]:
df5 = df.copy()
df5 = df5.drop(index=["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [16]:
exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

df2 = df.copy()
df2 = df2.drop("수학", axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [17]:
df3 = df.copy()
df3 = df3.drop(["영어", "음악"], axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [18]:
df4 = df.copy()
df4 = df4.drop(["영어", "음악"], axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [19]:
df5 = df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [20]:
# 행 선택

exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [21]:
label1 = df.loc["서준"]
print(label1)
print(type(label1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [22]:
position1 = df.iloc[0]
print(position1)
print(type(position1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [23]:
label2 = df.loc[["서준", "우현"]]
print(label2)
print(type(label2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [24]:
label3 = df.loc[["서준"]] # 인덱서 안에 리스트로 가져오면 dataframe형태로 가져옴
print(label3)
print(type(label3))

    수학  영어  음악   체육
서준  90  98  85  100
<class 'pandas.DataFrame'>

In [25]:
position2 = df.iloc[[0, 1]]
print(position2)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [26]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [27]:
label3 = df.loc["서준":"인아"]
print(label3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [28]:
position3 = df.iloc[0:2]
print(position3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [29]:
# 열 1개 선택

# 열 1개 선택: DataFrame객체["열이름"] 또는 DataFrame객체.열이름

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [30]:
math1 = df["수학"]
math1

0    90
1    80
2    70
Name: 수학, dtype: int64

In [31]:
english = df.영어
english

0    98
1    89
2    95
Name: 영어, dtype: int64

In [32]:
music_gym = df[["음악", "체육"]]
music_gym

    음악   체육
0   85  100
1   95   90
2  100   90

In [33]:
# 범위 슬라이싱

# 범위 슬라이싱: DataFrame객체.iloc[시작인덱스:끝인덱스:슬라이싱간격]

df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [34]:
# 원소 선택

# 인덱스이름: DataFrame객체.loc[행인덱스, 열이름]
# 정수위치인덱스: DataFrame객체.iloc[행번호, 열번호]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [35]:
df = df.set_index("이름")

In [36]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [37]:
a = df.loc["서준", "음악"]
print(a)

b = df.iloc[0,2]
print(b)

85
85

In [38]:
c = df.loc["서준", ["음악", "체육"]]
print(c)

d = df.iloc[0, [2, 3]]
print(d)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [39]:
e = df.loc["서준", "음악":"체육"]
print(e)

f = df.iloc[0, 2:]
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [40]:
g = df.loc[["서준", "우현"], ["음악", "체육"]]
print(g)

h = df.iloc[[0, 1], [2, 3]]
print(h)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [41]:
i = df.loc["서준":"우현", "음악":"체육"]
print(i)

j = df.iloc[0:2, 2:]
print(j)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [42]:
# 열추가

# 열추가: DataFrame객체["추가하려는 열 이름"] = 데이터 값

df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [43]:
exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [44]:
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [45]:
# 행 추가

# 행 추가: DataFrame.loc["새로운 행 이름"] = 데이터 값 (또는 배열)

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [46]:
print(df.loc[0:2])
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [47]:
df.loc[3] = 0
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [48]:
df.loc[4] = ["동규", 90, 80, 70, 60]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [49]:
df.loc["행5"] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [50]:
# 원소 값 변경

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)

df = df.set_index("이름")
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [52]:
df.iloc[0, 3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [58]:
df.loc["서준", "체육"] = 90
print(df)

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [59]:
df.loc["서준", ["음악", "체육"]] = 50
print(df)

df.loc["서준", ["음악", "체육"]] = 100, 50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90
    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [62]:
# 행, 열의 위치 바꾸기

# 행, 열 바꾸기: DataFrame객체.transpose() 또는 DataFrame.T
exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)

df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90