In [3]:
import pandas as pd
import numpy as np

In [4]:
dict_data = {
    "국어": 100,
    "영어": 80,
    "수학": 90
}

s1 = pd.Series(dict_data)
s1

국어    100
영어     80
수학     90
dtype: int64

In [5]:
percentage = s1 / 200
print(percentage)
print(type(percentage))

국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.Series'>

In [6]:
s1 = pd.Series({
    "국어": 100,
    "영어": 80,
    "수학": 90
})
s2 = pd.Series({
    "수학": 80,
    "국어": 90,
    "영어": 80,
    
})

print(s1)
print(s2)

국어    100
영어     80
수학     90
dtype: int64
수학    80
국어    90
영어    80
dtype: int64

In [7]:
sum = s1 + s2
print(sum)
print(type(sum))

국어    190
수학    170
영어    160
dtype: int64
<class 'pandas.Series'>

In [8]:
s1 - s2

국어    10
수학    10
영어     0
dtype: int64

In [9]:
s1 * s2

국어    9000
수학    7200
영어    6400
dtype: int64

In [10]:
s1 / s2

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [11]:
# NaN값이 있는 시리즈 연산

s1 = pd.Series({"국어": np.nan, "영어": 80, "수학": 90})
s2 = pd.Series({"수학": 80, "국어": 90})

print(s1)
print(s2)

add = s1 + s2
sub = s1 - s2
mul = s1 * s2
div = s1 / s2
print(div)
print()

result = pd.DataFrame([add, sub, mul, div], index = ["덧셈", "뺄셈", "곱셈", "나눗셈"])
print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
국어      NaN
수학    1.125
영어      NaN
dtype: float64

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [12]:
# 연산 메서드

s1 = pd.Series({"국어": np.nan, "영어": 80, "수학": 90})
s2 = pd.Series({"수학": 80, "국어": 90})

sr_add = s1.add(s2, fill_value=0)
sr_sub = s1.sub(s2, fill_value=0)
sr_mul = s1.mul(s2, fill_value=0)
sr_div = s1.div(s2, fill_value=0)

result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                      index = ["덧셈", "뺄셈", "곱셈", "나눗셈"])

print(result)

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [13]:
# 데이터 프레임 연산

import seaborn as sns

In [ ]:
titanic = sns.load_dataset("titanic")

df = titanic.loc[:, ["age", "fare"]]

In [15]:
addition = df + 10

addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [16]:
# 데이터프레임 vs 데이터프레임

titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "fare"]]

df.tail()

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75

In [17]:
addition = df + 10
addition.tail()

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [18]:
subtraction = addition - df
subtraction.tail()

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [20]:
sample1 = addition.tail()
sample2 = subtraction.tail().fillna(0.0)

sample2

      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0